language: python
branches:
  only:
    - gh-pages
    - /.*/
before_install:
 - sudo apt-get update
 - sudo apt-get install oracle-java8-installer
 - sudo update-java-alternatives -s java-8-oracle
install:
 - git clone https://github.com/w3c/respec.git
 - git clone https://github.com/dontcallmedom/webidl-checker.git
 - git clone https://github.com/dontcallmedom/widlproc
# - git clone https://github.com/halindrome/linkchecker.git
 - cd widlproc && make obj/widlproc && cd ..
 - pip install html5lib lxml html5validator
# - sudo apt-get install libwww-perl libcss-dom-perl
script:
 - mkdir build
 - phantomjs --ignore-ssl-errors=true --ssl-protocol=tlsv1 respec/tools/respec2html.js -e -w index.html build/output.html
 - python webidl-checker/webidl-check build/output.html
# - perl -T linkchecker/bin/checklink  -S 0  -q -b -X "^http(s)?:" build/output.html
 - html5validator --root build/
env:
  global:
    - WIDLPROC_PATH=$TRAVIS_BUILD_DIR/widlproc/obj/widlproc
    - URL="http://w3c.github.io/wake-lock/W3CTRMANIFEST"
    - DECISION="http://www.w3.org/2009/dap/track/actions/738"
    - secure: "TwvUyb5luZr5jm3Q+xQS86i4M/dsFLpGISfocHCXXo9GsNPzNfsg+xphep0G83SM9DAO34f6S3Own5QKP4VRYSPGBi16y8bm0YS6VjOEXHtRQgb4UPUZsa0KXABrbxbJcTBO4gByD4Wu5qLR74Htis4N5N6y8z1Mx1QPSDrpXbA="

after_success:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "gh-pages" ] ; then curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN" ; fi
